src/objects/Orchestrated_Action_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orchestrated Action Log</relationshipLabel>
        <relationshipName>Orchestrated_Action_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestrated Action Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Orchestrated Action Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orchestrated Action Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orchestrated_Action_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orchestrated Action Queue</relationshipLabel>
        <relationshipName>Orchestrated_Action_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orchestrated_Action_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestrated Action Log</label>
        <referenceTo>Orchestrated_Action_Log__c</referenceTo>
        <relationshipLabel>Orchestrated Action Queue</relationshipLabel>
        <relationshipName>Orchestrated_Action_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestrated Action Queue</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Orchestrated Action Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orchestrated Action Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Orc_BatchableActionOrchestrator.cls
global class Orc_BatchableActionOrchestrator implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts 
{
    public static final String ACTION_ERP_ACCOUNT_CREATE = 'ERP Create Account';
    public static final String ACTION_ERP_ACCOUNT_UPDATE = 'ERP Update Account';
    
    public class Orc_BatchableActionOrchestratorException extends Exception { }
    
    global List<Orchestrated_Action_Queue__c> targetQueueItems;
    global String targetQueryString = null;
    global List<String> batchIdList = null;

    global Orc_BatchableActionOrchestrator()
    {
        targetQueueItems = new List<Orchestrated_Action_Queue__c>();
        batchIdList = new List<String>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        targetQueryString =  'SELECT ID FROM Orchestrated_Action_Queue__c ' +
            					'WHERE (Account__r.ID != NULL) AND Orchestrated_Action_Log__c = NULL';

        return Database.getQueryLocator(targetQueryString);
    }
 
    global void execute(Database.BatchableContext BC, List<Orchestrated_Action_Queue__c> scope)
    {
        
    }
    
    global void finish(Database.BatchableContext BC)
    {
        Orc_ScheduledOrchestrationManagerHelper.abortAndReschedule();
    }
}